### ISSUE TITLE
Рефакторинг Regex и FiniteAutomaton

### ISSUE THREAD

**Issue by xendalm** [OnionGrief/Chipollino#270]
Добавляются промежуточные классы AbstractMachine и AlgExpression (наследники BaseObject)

**ToDo:**
- [x] метод `is_term` используется в одном месте и его логика не соответствует названию

- [x] рефакторинг `map` в `unordered_map` везде, где можно

- [x] убрать указатели на вектора `vector<Lexeme>*`  везде

**Comment by xendalm** [comment]
С AlgExpression уже можно работать (хотя есть еще что украсивить). Парсинг backref регулярок думаю сделать в той же функции, что и для обычных. Можно добавить флаг, в зависимости от которого буду возвращать ошибку, если встречаю недопустимый символ.

Часть задач по дальнейшему рефакторингу хочу отдать человеку, который реализовывал алгоритмы @dak151449. 
Все они касаются Глушкова.
- [ ] метод `is_term` используется в одном месте и его логика не соответствует названию

- [ ] рефакторинг `map` в `unordered_map` везде, где можно

- [ ] убрать указатели на вектора `vector<Lexeme>*`  везде
